services:
  taxpayer-front:
    image: $IMAGE_NAME
    hostname: $CI_PROJECT_PATH_SLUG.$ENVIRONMENT
    restart: always
    ports:
      - 14900:80
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '3'
    networks:
      - taxpayer

networks:
  taxpayer:
    driver: bridge
